/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSpotifyNowPlayingRouteImport } from './routes/api.spotify.now-playing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyNowPlayingRoute = ApiSpotifyNowPlayingRouteImport.update({
  id: '/api/spotify/now-playing',
  path: '/api/spotify/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/spotify/now-playing': typeof ApiSpotifyNowPlayingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/spotify/now-playing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/spotify/now-playing'
  id: '__root__' | '/' | '/api/spotify/now-playing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSpotifyNowPlayingRoute: typeof ApiSpotifyNowPlayingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/now-playing': {
      id: '/api/spotify/now-playing'
      path: '/api/spotify/now-playing'
      fullPath: '/api/spotify/now-playing'
      preLoaderRoute: typeof ApiSpotifyNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSpotifyNowPlayingRoute: ApiSpotifyNowPlayingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
